# Generated by Django 3.1.5 on 2021-01-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Avilable_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.avilable', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='task',
            name='ChillVariations_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chillvariations', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='task',
            name='Region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.region', verbose_name='Регион'),
        ),
    ]
