# Generated by Django 3.1.5 on 2021-01-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_task_chilltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avilable',
            name='isAvilable',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='Avilable_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.avilable', verbose_name='ID поездки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ChillVariations_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chillvariations', verbose_name='Вид путешествия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Pricing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pricing', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Priority_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.priority', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='taskdate',
            name='dateIn',
            field=models.DateField(verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='taskdate',
            name='dateOut',
            field=models.DateField(verbose_name='Дата заключения'),
        ),
        migrations.AlterField(
            model_name='tasktime',
            name='timeIn',
            field=models.TimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='tasktime',
            name='timeOut',
            field=models.TimeField(verbose_name='Время заключения'),
        ),
    ]
