# Generated by Django 3.1.5 on 2021-01-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210117_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingplace',
            name='Region_id',
        ),
        migrations.AddField(
            model_name='ratingplace',
            name='Task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Регион'),
        ),
    ]
