# Generated by Django 3.1.5 on 2021-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210117_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='chillvariations',
            name='Pricing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pricing', verbose_name='Возможная цена'),
        ),
        migrations.AddField(
            model_name='priority',
            name='TaskDate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.taskdate', verbose_name='Дата поездки'),
        ),
        migrations.AlterField(
            model_name='ratingplace',
            name='Task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Название тура'),
        ),
    ]
